export { default as Home } from './home'
export { default as Layout } from './layout'
export { default as News } from './news'
export { default as Rent } from './rent'
export { default as Sold } from './sold'